spring:
  application:
    name: jpa
  H2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    initialize: true
    sql-script-encoding: UTF-8
    username: sa
    password: sa
  jpa:
    #database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
#server:
#  servlet:
#    context-path: /jpa